[logging]
type = "console"
threshold = "debug"        
file_path = "workflow.log" 
log_folder = "logs"        
max_file_size_mb = 1
http_endpoint = "https://logs.example.com"
http_timeout_seconds = 5
show_filename = true
show_module = true
console_colors = true
log_format = "[{level}] [{timestamp}] {message}"
timestamp_format = "%Y-%m-%d %H:%M:%S"
show_level_prefix = true
buffer_size = 0
force_flush = true