[logging]
type = "file"
file_path = "workflow.log"
http_endpoint = "https://logs.example.com"
threshold = "debug"

[metrics]
type = "http"
file_path = "metrics.json"
http_endpoint = "https://metrics.example.com"