[workspace]
members = [
    "engine", "engine_core",
    "plugin_core",
    "plugins/plugin_wifi"
]
resolver = "2"

[workspace.dependencies]
axum = { version = "0.7", features = ["macros", "http1", "tokio"] }
tokio = { version = "1.36", features = ["full"] }
libloading = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tower = "0.4"
async-trait = "0.1"
plugin_core = { path = "../plugin_core" }
engine_core = { path = "../engine_core"}
