[general]
product_family = "Echo"
execution_plan_version = "1.3"
update_from = "s3"
update_path_root = "s3://my-bucket/execution_plans/"

[[plugins]]
name = "plugin_wifi"
plugin_route = "wifi"
version = "3.4"
plugin_location_type = "s3"
plugin_base_path = "https://my-bucket.s3.amazonaws.com/plugins/plugin_wifi.dylib"
team_name = "Edge Connectivity Team"
engineering_contact_email = "wifi-eng@example.com"
operation_contact_email = "wifi-ops@example.com"
run_async = false
visible_in_ui = true
plugin_description = "Wi-Fi scan and connect flow"

[[plugins]]
name = "plugin_settings"
plugin_route = "settings"
version = "1.1"
plugin_location_type = "local"
plugin_base_path = "./"
team_name = "Kindle Product Team"
engineering_contact_email = "kindle-settings-eng@example.com"
operation_contact_email = "kindle-settings-ops@example.com"
run_async = false
visible_in_ui = true
plugin_description = "Collect device specific user settings"
