[general]
product_family = "Echo"
execution_plan_version = "1.3"
update_from = "s3"
update_path_root = "./ext_plan"

[[plugins]]
name = "plugin_example"
plugin_description = "This is an example plugin that does not exist"
plugin_route = "example"
version = "3.4"
plugin_location_type = "s3"
plugin_base_path = "https://my-bucket.s3.amazonaws.com/plugins/plugin_example.dylib"
team_name = "Example Plugin Team"
engineering_contact_email = "example-eng@example.com"
operation_contact_email = "example-ops@example.com"
run_async = false
visible_in_ui = true
run_after_event_name = "TermsCompleted"
completed_event_name = "ExampleCompleted"

[[plugins]]
name = "plugin_settings"
plugin_description = "Collect device specific user settings"
plugin_route = "settings"
version = "1.1"
plugin_location_type = "local"
plugin_base_path = "./"
team_name = "Echo Product Team"
engineering_contact_email = "echo-settings-eng@example.com"
operation_contact_email = "echo-settings-ops@example.com"
run_async = false
visible_in_ui = true
run_after_event_name = "LoginCompleted"
completed_event_name = "SettingsCompleted"

[[plugins]]
name = "plugin_howto"
plugin_description = "plugin_howto description"
plugin_route = "howto"
version = "4.1"
plugin_location_type = "local"
plugin_base_path = "./"
team_name = "PluginHowto Product Team"
engineering_contact_email = "plugin_howto-eng@example.com"
operation_contact_email = "plugin_howto-ops@example.com"
run_async = true
visible_in_ui = true                                        # Headless or UI?
run_after_event_name = "SettingsCompleted"         # This is your entry point
completed_event_name = "HowtoCompleted"          # Raise this event when you are done

[[plugins]]
name = "plugin_tutorial"
plugin_description = "plugin_tutorial description"
plugin_route = "tutorial"
version = "4.1"
plugin_location_type = "local"
plugin_base_path = "./"
team_name = "PluginTutorial Product Team"
engineering_contact_email = "plugin_tutorial-eng@example.com"
operation_contact_email = "plugin_tutorial-ops@example.com"
run_async = true
visible_in_ui = true                                        # Headless or UI?
run_after_event_name = "ProvisionCompleted"         # This is your entry point
completed_event_name = "TutorialCompleted"          # Raise this event when you are done

[handoffs]
handoff_events = ["HowtoCompleted", "TutorialCompleted"]
