[general]
product_family = "Echo"
execution_plan_version = "1.3"
update_from = "s3"
update_path_root = "s3://my-bucket/execution_plans/"

[[plugins]]
name = "plugin_example"
plugin_description = "This is an example plugin that does not exist"
plugin_route = "example"
version = "3.4"
plugin_location_type = "s3"
plugin_base_path = "https://my-bucket.s3.amazonaws.com/plugins/plugin_example.dylib"
team_name = "Example Plugin Team"
engineering_contact_email = "example-eng@example.com"
operation_contact_email = "example-ops@example.com"
run_async = false
visible_in_ui = true
run_after_event_name = "TermsCompleted"
completed_event_name = "ExampleCompleted"

[[plugins]]
name = "plugin_settings"
plugin_description = "Collect device specific user settings"
plugin_route = "settings"
version = "1.1"
plugin_location_type = "local"
plugin_base_path = "./"
team_name = "Kindle Product Team"
engineering_contact_email = "kindle-settings-eng@example.com"
operation_contact_email = "kindle-settings-ops@example.com"
run_async = false
visible_in_ui = true
run_after_event_name = "LoginCompleted"
completed_event_name = "SettingsCompleted"

