[package]
name = "engine_desktop_ui"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
engine = { path = "../engine" }
tokio = { version = "1.37", features = ["full"] }
wry = "0.36"
tao = "0.27"